USE master 
go 
DROP DATABASE  MEDICINA_DB 
 GO
CREATE DATABASE MEDICINA_DB


GO
use MEDICINA_DB
GO

CREATE TABLE ESPECIALIDADES(
IDESPECIALIDAD BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
ESPECIALIDAD VARCHAR(50) NOT NULL,
ACTIVO int NOT NULL
)
GO
CREATE TABLE HORARIOS(
IDHORARIO BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
TURNO VARCHAR (20) NOT NULL,
HORAENTRADA BIGINT NOT NULL,
HORASALIDA BIGINT NOT NULL,
ACTIVO int NOT NULL
)
GO
CREATE TABLE LOCALIDADES(
IDLOCALIDAD BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
LOCALIDAD VARCHAR(50) NOT NULL,
CP BIGINT NOT NULL,
ACTIVO int NOT NULL
)

GO
CREATE TABLE MEDICOS(
IDMEDICO BIGINT  NOT NULL PRIMARY KEY IDENTITY(1,1),
IDHORARIO BIGINT NOT NULL FOREIGN KEY REFERENCES HORARIOS(IDHORARIO),
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
DNI BIGINT NOT NULL UNIQUE,
DIRECCION VARCHAR(50) NOT NULL,
IDLOCALIDAD BIGINT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(IDLOCALIDAD),
CELULAR BIGINT,
TELEFONO BIGINT,
EMAIL VARCHAR (50),
FECHA_NACIMIENTO DATE NOT NULL,
SEXO VARCHAR (10),
ACTIVO int NOT NULL
)
GO
CREATE TABLE PACIENTES(
IDPACIENTE BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
DNI BIGINT NOT NULL UNIQUE,
DIRECCION VARCHAR(50) NOT NULL,
IDLOCALIDAD BIGINT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(IDLOCALIDAD),
CELULAR BIGINT,
TELEFONO BIGINT,
EMAIL VARCHAR (50),
FECHA_NACIMIENTO DATE NOT NULL,
SEXO VARCHAR (10),
ACTIVO int NOT NULL
) 

GO
CREATE TABLE ESPECIALIDADES_X_MEDICO(
IDGENERAL BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDMEDICO BIGINT NOT NULL FOREIGN KEY REFERENCES MEDICOS(IDMEDICO),
IDESPECIALIDAD BIGINT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES(IDESPECIALIDAD),
ENTRADA BIGINT NOT NULL,
SALIDA BIGINT NOT NULL,
ACTIVO int NOT NULL

)

GO
create  TABLE TURNOS(
IDTURNO BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDPACIENTE BIGINT NOT NULL FOREIGN KEY REFERENCES PACIENTES (IDPACIENTE),
IDESPECIALIDAD bigint NOT NULL foreign key references ESPECIALIDADES (IDESPECIALIDAD),
IDMEDICO BIGINT NOT NULL FOREIGN KEY REFERENCES MEDICOS (IDMEDICO),
FECHATURNO DATE NOT NULL,
HORATURNO BIGINT NOT NULL,
OBSERVACIONES VARCHAR (150),
ACTIVO INT NOT NULL
)
GO
CREATE TABLE USUARIOS
(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	USUARIO VARCHAR(30) NOT NULL,
	CONTRASENIA VARCHAR(30) NOT NULL,
	ACTIVO INT NOT NULL 
)
GO
INSERT INTO USUARIOS (USUARIO,CONTRASENIA,ACTIVO)
VALUES('ADMIN','ADMIN',1)
INSERT INTO USUARIOS (USUARIO,CONTRASENIA,ACTIVO)
VALUES('RECEPCIONISTA','RECEPCIONISTA',1)
INSERT INTO USUARIOS (USUARIO,CONTRASENIA,ACTIVO)
VALUES('MEDICO','MEDICO',1)
GO
/*LOCALIDADES*/
INSERT INTO LOCALIDADES(LOCALIDAD,CP,ACTIVO) VALUES('MAQUINISTA SAVIO',1620,1)
INSERT INTO LOCALIDADES(LOCALIDAD,CP,ACTIVO) VALUES('GARIN',1621,1)
INSERT INTO LOCALIDADES(LOCALIDAD,CP,ACTIVO) VALUES('ESCOBAR',1622,1)
GO

/*HORARIOS*/
INSERT INTO HORARIOS(TURNO,HORAENTRADA,HORASALIDA,ACTIVO)
VALUES('LUN A VIE MAÑANA',0600,1200,1)
INSERT INTO HORARIOS(TURNO, HORAENTRADA,HORASALIDA,ACTIVO)
VALUES('LUN A VIE TARDE',1200,1800,1)
INSERT INTO HORARIOS(TURNO,HORAENTRADA ,HORASALIDA,ACTIVO)
VALUES('LUN A VIE NOCHE',1800,2400,1)
INSERT INTO HORARIOS(TURNO, HORAENTRADA,HORASALIDA,ACTIVO)
VALUES('FERIADOS',0000,2400,1)
INSERT INTO HORARIOS(TURNO,HORAENTRADA ,HORASALIDA,ACTIVO)
VALUES('SABADOS',0000,2400,1)
INSERT INTO HORARIOS(TURNO,HORAENTRADA ,HORASALIDA,ACTIVO)
VALUES('DOMINGO',0000,2400,1)
GO
/* MEDICOS*/

INSERT INTO MEDICOS (IDHORARIO ,NOMBRE ,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES(1,'MARIANO','LENCINA',12345678,'CALLE FALSA 123',1,22334455,11112222,'CHULO@CAPO.COM','1983/08/11','MASCULINO',1)
INSERT INTO MEDICOS (IDHORARIO,NOMBRE ,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES(2,'FERNANDO','DE PALMA',22222222,'AV SAN MARTIN 123',2,222333444,444333222,'FER@JCP.COM','1983/12/11','MASCULINO',1)
INSERT INTO MEDICOS(IDHORARIO ,NOMBRE ,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES(3,'DANIEL','KLOSTER',123455,'AV FELIZ 345',3,333444555,555444333,'DANIEL@JCP.COM','1980/05/25','MASCULINO',1)
GO
/* PACIENTES*/
INSERT INTO PACIENTES(NOMBRE,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES('MAXIMILIANO','SAR',12345678,'CALLE FALSA 123',1,22334455,11112222,'MAXI@JCP.COM','1960/05/15','MASCULINO',1)
INSERT INTO PACIENTES(NOMBRE,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES('ANGEL','SIMON',22222222,'AV SAN MARTIN 123',2,222333444,444333222,'ANGEL@JCP.COM','1965/08/11','MASCULINO',1)
INSERT INTO PACIENTES(NOMBRE,APELLIDO,DNI,DIRECCION,IDLOCALIDAD,CELULAR,TELEFONO,EMAIL,FECHA_NACIMIENTO,SEXO,ACTIVO)
VALUES('DANIEL','KLOSTER',123455,'AV FELIZ 345',3,333444555,555444333,'DANIEL@JCP.COM','1962/04/20','MASCULINO',1)

GO

/* ESPECIALIDADES */
INSERT INTO ESPECIALIDADES (ESPECIALIDAD,ACTIVO) VALUES('PEDIATRIA',1)
INSERT INTO ESPECIALIDADES (ESPECIALIDAD,ACTIVO) VALUES('CARDIOLOGIA',1)
INSERT INTO ESPECIALIDADES (ESPECIALIDAD,ACTIVO) VALUES('NUTRICIONISTA',1)

GO
insert into TURNOS (IDPACIENTE,IDESPECIALIDAD,IDMEDICO,FECHATURNO,HORATURNO,OBSERVACIONES,ACTIVO )
values (1,1,1,'1983/12/11',1200,'masd',1)
GO
INSERT INTO ESPECIALIDADES_X_MEDICO(IDMEDICO,IDESPECIALIDAD,ENTRADA,SALIDA,ACTIVO)
VALUES (1,1,0600,1200,1),(2,2,1200,1800,1),(3,3,1800,2400,1)
/*PROCEDIMIENTOS ALMACENADOS*/
  /* DROP PROCEDURE altaEspecialidad*/
    go
    create procedure altaEspecialidad
                @especialidad varchar(50)
                as
                 insert into ESPECIALIDADES  values (@especialidad, 1)